### ISSUE TITLE
jumalauta's skinke demo doesn't animate properly

### ISSUE THREAD

**Issue by iamgreaser** [supergameherm/supergameherm#21] opened 2014-12-30 22:35 UTC
This may be releated to #15 and will probably be solved by solving #15 but whatever.
ROM: http://gameboy.modermodemet.se/en/demo/147

**Comment by Elizafox** [comment] 2015-01-02 20:40
Possibly related to #12

**Comment by Elizafox** [comment] 2015-01-04 04:40
This HAS to be vblank related... I disassembled the ROM: http://i.imgur.com/29YU8xc.png - I am positive the vblank timings are wrong now.

**Comment by Elizafox** [comment] 2015-01-04 12:09
Possible duplicate of #22

**Closed by Elizafox** 2015-01-04 12:09 UTC
Labels: bug, duplicate

**Comment by iamgreaser** [comment] 2015-01-07 06:54
This was NOT a duplicate. It was due to the demo abusing SB (serial in/out data) as a scratch register.

This has been fixed in c11c337 and now has a separate problem to be solved.
